mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: '*'
when@test:
    mercure:
        hubs:
            default:
                url: 'test_mercure_url'
                public_url: 'test_mercure_public_url'
                jwt:
                    secret: 'test_mercure_secret'
                    publish: '*'
