framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        default_bus: command.bus
        buses:
            command.bus: ~
            query.bus: ~
        transports:
            sync: 'sync://'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            'App\Post\Application\Command\Message\CreatePostMessage': sync
            'App\Post\Application\Query\Message\PostByIdQuery': sync
            'App\User\Application\Command\Message\CreateUserMessage': sync
            'App\User\Application\Query\Message\UserByIdQuery': sync
        


# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
