nelmio_api_doc:
    documentation:
        info:
            title: Social Media API
            description: Social Media API developed in Symfony 6.4
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
