when@dev:
    app.swagger_ui:
        path: /api/doc
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

when@test:
    app.swagger_ui:
        path: /api/doc
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
post_controllers:
    resource:
        path: ../src/Post/Api/Controller/
        namespace: App\Post\Api\Controller
    type: attribute
user_controllers:
    resource:
        path: ../src/User/Api/Controller/
        namespace: App\User\Api\Controller
    type: attribute